#!/usr/bin/env bash

if
  [[ -s "/home/framgia-ror/.rvm/gems/ruby-2.3.1/environment" ]]
then
  source "/home/framgia-ror/.rvm/gems/ruby-2.3.1/environment"
  exec nokogiri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/framgia-ror/.rvm/gems/ruby-2.3.1/environment'" >&2
  exit 1
fi
