#!/usr/bin/env bash

if
  [[ -s "/home/framgia-ror/.rvm/gems/ruby-2.4.0/environment" ]]
then
  source "/home/framgia-ror/.rvm/gems/ruby-2.4.0/environment"
  exec sprockets "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/framgia-ror/.rvm/gems/ruby-2.4.0/environment'" >&2
  exit 1
fi
